kind: Service
apiVersion: v1
metadata:
  name:  front-lb-b
  labels:
    app: front-lb-b
spec:
  selector:
    app:  front-b
  type:  LoadBalancer
  ports:
  - protocol: "TCP"
    # Port accessible inside cluster
    port: 80
    # Port to forward to inside the pod
    targetPort: 80
    # Port accessible outside cluster
    nodePort: 30002