apiVersion: v1
data:
  URL-BACKEND-FINTECH: amRiYzpteXNxbDovL214LmNvbS5zbWkuc2VydmljZXM6MzAyMDEvY3Vyc28=
    #jdbc:mysql://mx.com.smi.services:30201/curso
  USERDB: cm9vdA==
  #root=
  PWDDB: YWRtaW4xMjM=
    #admin123
kind: Secret
metadata:
  name: credenciales-backend-fintech
type: Opaque