apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    project: nginx
    environment: testing
spec:
  type: NodePort
  selector:
    project: nginx
    environment: testing
  ports:
  - protocol: TCP
    port: 80
