apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    project: frontend-krece
    environment: testing
spec:
  containers:
  - name: nginx
    image: nginx:1.17.6
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "250m"
    ports:
      - containerPort: 80
