apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-a
  labels:
    app: db-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-a
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db-a
    spec:
      containers:
      - image: erdnando/db-fintech
        name: db-a
        ports:
        - containerPort: 3306
          name: db-a
        volumeMounts:
        - name: mysql-persistent-storage1
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage1
        persistentVolumeClaim:
          claimName: mysql-pvc-claim1
