apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-b
  labels:
    app: db-b
spec:
  replicas: 0
  selector:
    matchLabels:
      app: db-b
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db-b
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: my_db
        - name: MYSQL_USER
          value: test
        - name: MYSQL_PASSWORD
          value: Welcome1
        - name: MYSQL_ROOT_HOST
          value: "%"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage-b
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage-b
        persistentVolumeClaim:
          claimName: mysql-pv-claim-b
