apiVersion: v1
kind: Pod
metadata:
  name: nginx-cm
spec:
  containers:
  - name: nginx
    image: nginx
    env:
      - name: ENVIRONMENT_TEST
        valueFrom:
          configMapKeyRef:
            name: test-cm
            key: variable1
      - name: DATABASE_ENDPOINT
        valueFrom:
          configMapKeyRef:
            name: test-cm2
            key: variable2
