apiVersion: v1
kind: Pod
metadata:
  name: nginx-secrets-mount-envvar
spec:
  containers:
  - name: nginx
    image: nginx:1.17.6
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: credenciales-manifest
            key: username
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: credenciales-manifest
            key: password
      - name: SECRET_TEST
        valueFrom:
          secretKeyRef:
            name: credenciales-manifest
            key: username