apiVersion: v1
kind: Pod
metadata:
  name: nginx-limits
spec:
  restartPolicy: Always
  containers:
  - name: web
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
