kind: Service
apiVersion: v1
metadata:
  name:  backend-lb-a
  labels:
    app: backend-lb-a
spec:
  selector:
    app:  backend-a
  type:  LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30101
  - name: admin
    port: 9990
    targetPort: 9990
    nodePort: 30102