apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-b
  labels:
    app: backend-b
spec:
  replicas: 0
  selector:
    matchLabels:
      app: backend-b
  template:
    metadata:
      labels:
        app: backend-b
    spec:
      containers:
      - name: backend-b
        image: jboss/wildfly
        ports:
        - containerPort: 8080
