apiVersion: v1
data:
  URL-BACKEND-FINTECH: amRiYzpteXNxbDovL214LmNvbS5zbWkuc2VydmljZXM6MzAyMDEvY3Vyc28=
    #jdbc:mysql://mx.com.smi.services:30201/curso
  USERDB: cm9vdA==
  #root=
  PWDDB: YWRtaW4xMjM=
    #admin123
kind: Secret
metadata:
  name: credenciales-backend-fintech
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-a
  labels:
    app: backend-a
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-a
  template:
    metadata:
      labels:
        app: backend-a
    spec:
      imagePullSecrets:
      - name: pullsecret
      containers:
      - name: backend-a
        #from docker hub  erdnando/backend-fintech
        #from private repo    mx.com.smi.services:30402/backend-fintech:latest
        image: mx.com.smi.services:30402/backend-fintech:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        - containerPort: 9990
        livenessProbe:
          httpGet:
            path: /Aplicacion/livenessProbe
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /Aplicacion/readynessProbe
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        env:
        - name: URL-BACKEND-FINTECH
          valueFrom:
            secretKeyRef:
              name: credenciales-backend-fintech
              key: URL-BACKEND-FINTECH
        - name: USERDB
          valueFrom:
            secretKeyRef:
              name: credenciales-backend-fintech
              key: USERDB
        - name: PWDDB
          valueFrom:
            secretKeyRef:
              name: credenciales-backend-fintech
              key: PWDDB
---
kind: Service
apiVersion: v1
metadata:
  name:  backend-lb-a
  labels:
    app: backend-lb-a
spec:
  selector:
    app:  backend-a
  type:  LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30101
  - name: admin
    port: 9990
    targetPort: 9990
    nodePort: 30102