apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-a
  labels:
    app: jenkins-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-a
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jenkins-a
    spec:
      containers:
      - name: jenkins-a
        image: erdnando/jenkins-fintech
        ports:
        - containerPort: 8080
        - containerPort: 50000
        volumeMounts:
          - name: jenkins-home
            mountPath: /var/jenkins_home
          - name: docker-sock
            mountPath: /var/run/docker.sock
      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-pvc-claim
        - name: docker-sock
          hostPath:
            # directory location on host
            path: /var/run/docker.sock

#en minikube ssh dar permisos:
#  sudo chown 1000 /var/jenkins_home/

 #hostPath:
            # directory location on host
 #           path: /var/jenkins_home

#4c56b07756f24cb7a2ee61887abe6c70
#https://github.com/wardviaene/docker-demo.git
#volumeMounts:
#          - name: jenkins-home
#            mountPath: /var/jenkins_home
#      volumes:
#        - name: jenkins-home
#          persistentVolumeClaim:
#            claimName: jenkins-pvc-claim
#minikube ssh sudo chown 1000 /data/jenkins -pv 