FROM jenkins/jenkins:lts



EXPOSE 8080
EXPOSE 50000

VOLUME /var/jenkins_home/


#make repository in docker-hub : erdnando/jenkins-fintech
#docker rmi image erdnando/jenkins-fintech
#build
#docker build -t erdnando/jenkins-fintech:latest .
#local test
#docker run -it -p 8080:80 --name jenkins-fintech jenkins/jenkins-fintech
#push
#docker push erdnando/jenkins-fintech:latest
